/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],

  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#380038',
        'secondary-container': '#fe00fe',
        secondary: '#ffabf3',
        'surface-container-high': '#2a2a2a',
        surface: '#131313',
        'surface-tint': '#00dddd',
        'on-surface': '#e2e2e2',
        'surface-container-highest': '#353535',
        'on-secondary-container': '#500050',
        'surface-container': '#1f1f1f',
        'on-tertiary-fixed': '#410000',
        'surface-variant': '#353535',
        'on-error-container': '#ffdad6',
        'on-tertiary': '#690100',
        'on-primary-container': '#007070',
        'error-container': '#93000a',
        'surface-container-low': '#1b1b1b',
        'surface-bright': '#393939',
        'on-primary': '#003737',
        tertiary: '#ffffff',
        'surface-dim': '#131313',
        'on-tertiary-container': '#cc0100',
        'on-surface-variant': '#b9cac9',
        'secondary-fixed-dim': '#ffabf3',
        'inverse-surface': '#e2e2e2',
        'tertiary-container': '#ffdad4',
        'inverse-primary': '#006a6a',
        'primary-fixed-dim': '#00dddd',
        'on-secondary': '#5b005b',
        'on-error': '#690005',
        'primary-container': '#00fbfb',
        'on-tertiary-fixed-variant': '#930100',
        'tertiary-fixed-dim': '#ffb4a8',
        'on-background': '#e2e2e2',
        error: '#ffb4ab',
        background: '#131313',
        'on-primary-fixed': '#002020',
        'surface-container-lowest': '#0e0e0e',
        outline: '#839493',
        'tertiary-fixed': '#ffdad4',
        'on-primary-fixed-variant': '#004f4f',
        'inverse-on-surface': '#303030',
        'outline-variant': '#3a4a49',
        primary: '#ffffff',
        'primary-fixed': '#00fbfb',
        'on-secondary-fixed-variant': '#810081',
        'secondary-fixed': '#ffd7f5',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk'],
        body: ['Inter'],
        label: ['Space Grotesk'],
      },
    },
  },
  plugins: [],
}
